name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  EIGEN3_INCLUDE_DIR: /usr/include/eigen3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
            
      - name: Install Dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu') 
        run: |
          sudo apt-get update
          sudo apt-get install -y gnuplot
          sudo apt-get install -y libeigen3-dev
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libgsl-dev
          sudo apt-get install -y libarchive-dev
          sudo apt-get install -y build-essential
          sudo apt-get install -y cmake
      
      - name: Install Dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install gnuplot eigen boost gsl libarchive cmake
      
      - name: Configure CMake
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLibArchive_DIR=/usr/lib/x86_64-linux-gnu/cmake/libarchive
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            LIBARCHIVE_DIR=$(brew --prefix libarchive)
            export LibArchive_INCLUDE_DIR="${LIBARCHIVE_DIR}/include"
            export LibArchive_LIBRARY="${LIBARCHIVE_DIR}/lib/libarchive.dylib"            
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_OPENMP=OFF
          fi
          
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
